ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls', namespace='members')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'members'
urlpatterns = [
    path('login_user/', views.login_user, name="login_user"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('register_user/', views.register_user, name="register_user"),
    path('password-reset/', PasswordResetView.as_view(template_name='authentication/password_reset.html'),
         name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'),
         name='password_reset_complete'),
]

store/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', StoreView.as_view(), name="store"),
    path('cart/', CartView.as_view(), name="cart"),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('update_item/', UpdateitemView.as_view(), name="update-item"),
    path('process_order/', views.processOrder, name="process-order"),
    path('search_product/', SearchProductView.as_view(), name="search-product"),
    path('contact_us/', views.contact_us, name="contact-us"),
    path('add_product/', views.AddProductView.as_view(), name="add-product"),
    path('update_product/<product_id>', views.update_product, name="update-product"),
    path('delete_product/<product_id>', views.delete_product, name="delete-product"),

]

store/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name= models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True)
    image = models.ImageField(null=True, blank=True)
    category= models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)

    @property
    def imgURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_orderd = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderItems = self.orderitem_set.all()
        for i in orderItems:
            if i.product.digital == False:
                shipping = True
            return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    adress = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.adress

store/forms.py
from django import forms
from django.forms import ModelForm
from .models import Product, Category


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Product Name'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Product Price'}),
            'digital': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'})
        }
        labels = {
            'name': '',
            'price': '',
        }


class ContactForm(forms.Form):
    name = forms.CharField(label="", max_length=100,
                           widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Name'}), )
    email = forms.EmailField(label="",
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Your Email'}))
    subject = forms.CharField(label="", max_length=500,
                              widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject:'}))
    message = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 4, 'cols': 40, 'class': 'form-control', 'placeholder': 'Your Message..'}),
        label=''
    )

store/views.py
from django.core.mail import BadHeaderError, send_mail
from django.shortcuts import render, redirect
from .models import *
from .utils import cookieCart, cartData, guestOrder
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views import View
import json
import datetime
from .forms import ProductForm, ContactForm
from django.contrib import messages


class StoreView(View):
    template_name = 'store/store.html'

    def get(self, request):
        data = cartData(request)
        order = data['order']
        items = data['items']
        cartItems = data['cartItems']
        category = request.GET.get('category')
        sort_by = request.GET.get("sort")
        products = Product.objects.all()
        if category:
            products = products.filter(category__name=category)

        if sort_by == "l2h":
            products = products.order_by("price")
        elif sort_by == "h2l":
            products = products.order_by("-price")
        else:
            products = products.order_by("name")

        categories = Category.objects.all()
        context = {'products': products, 'cartItems': cartItems, 'categories': categories, 'category': category}
        return render(request, self.template_name, context)


class CartView(View):
    template_name = 'store/cart.html'

    def get(self, request):
        data = cartData(request)
        items = data['items']
        order = data['order']
        cartItems = data['cartItems']
        categories = Category.objects.all()
        context = {'items': items, 'order': order, 'cartItems': cartItems, 'categories': categories}
        return render(request, self.template_name, context)


class CheckoutView(View):
    template_name = 'store/checkout.html'

    def get(self, request):
        data = cartData(request)
        items = data['items']
        order = data['order']
        cartItems = data['cartItems']
        context = {'items': items, 'order': order, 'cartItems': cartItems}
        return render(request, self.template_name, context)


class UpdateitemView(View):
    def post(self, request):
        data = json.loads(request.body)
        productId = data['productId']
        action = data['action']

        print('Action:', action)
        print('ProductId:', productId)

        customer = request.user.customer
        product = Product.objects.get(id=productId)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

        orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

        if action == 'add':
            orderItem.quantity = orderItem.quantity + 1
        elif action == 'remove':
            orderItem.quantity = orderItem.quantity - 1
        orderItem.save()

        if orderItem.quantity <= 0:
            orderItem.delete()

        return JsonResponse('Item was added', safe=False)

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )

    return JsonResponse('Payment submitted..', safe=False)

# ------ SEARCH-PRODUCTS ------
class SearchProductView(View):
    template_name = 'store/search_product.html'
    def get(self, request):
        return render(request, self.template_name, {})

    def post(self, request):
        searched = request.POST.get('searched')
        searched_products = Product.objects.filter(name__contains=searched)
        return render(request, self.template_name, {'searched': searched, 'searched_products': searched_products})


# ------ CRUD Products ------
class AddProductView(View):
    def get(self, request):
        form = ProductForm()
        submitted = False
        if 'submitted' in request.GET:
            submitted = True
        categories = Category.objects.all()
        return render(request, 'store/add_product.html',
                      {'categories': categories, 'form': form, 'submitted': submitted})

    def post(self, request):
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # return HttpResponseRedirect('/add_product?submitted=True')
            messages.success(request, "Product added successfully!")
            return redirect('store')
        categories = Category.objects.all()
        return render(request, 'store/add_product.html', {'categories': categories, 'form': form})


def update_product(request, product_id):
    product = Product.objects.get(pk=product_id)
    form = ProductForm(request.POST or None, instance=product)
    if form.is_valid():
        form.save()
        messages.success(request, "Product updated successfully!")
        return redirect('store')
    return render(request, 'store/update_product.html', {'product': product, 'form': form})


def delete_product(request, product_id):
    try:
        item = OrderItem.objects.get(product__id=product_id)
        item.delete()
    except:
        pass
    product = Product.objects.get(pk=product_id)
    product.delete()
    messages.success(request, "Product deleted successfully!")
    return redirect('store')

# ------ CONTACT US ------
def contact_us(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = request.POST.get("subject", "")
            message = request.POST.get("message", "")
            from_email = request.POST.get("email", "")
            if subject and message and from_email:
                try:
                    send_mail(subject, message, from_email, ["contact@shopwave.com"])
                except BadHeaderError:
                    messages.success(request, "Invalid header found.")
                    return redirect(request.get_full_path())
                messages.success(request,
                                 "Thanks! Our team will come back to you within a matter of hours to help you.")
                return redirect('store')

            else:
                messages.success(request, "Make sure all fields are entered and valid.")
                return redirect(request.get_full_path())
            return redirect('store')
    else:
        form = ContactForm()

    return render(request, 'store/contact_us.html', {'form': form})

store/templates/store/add_product.html
{% extends 'store/index.html' %}
{% load static %}
{% block content %}
<h1 class="mb-3 display-4 fw-bolder">Add Products:</h1>
<!--{% if submitted %}-->
<!--<div class="alert alert-warning alert-dismissible fade show" role="alert">-->
<!--    Your form was submitted successfully!!-->
<!--    <button aria-label="Close" class="btn-close" data-bs-dismiss="alert" type="button"></button>-->
<!--</div>-->
<!--{% else %}-->
{% if user.is_staff %}

<form action="" method="POST" enctype="multipart/form-data">
    <!-- Product Name input -->
    {% csrf_token %}
    {{form.as_p}}
    <!-- Submit button -->
    <button class="btn btn-secondary btn-block mb-4" type="submit">Add Product</button>
</form>
{% else %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    Acess Denied!! only admin can access this..
    <button aria-label="Close" class="btn-close" data-bs-dismiss="alert" type="button"></button>
</div>
{% endif %}
{% endif %}
{% endblock content %}

store/templates/store/cart.html
{% extends 'store/index.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'store' %}">&#x2190; Continue Shopping</a>
                <br>
                <br>
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
                        <th><h5>Total: <strong>{{order.get_cart_total|floatformat:2}} DT</strong></h5></th>
                        <th>
                            <a style="float: right; margin:5px" class="btn btn-secondary" href="{% url 'checkout' %}">Checkout</a>
                        </th>
                    </tr>
                </table>
            </div>
            <br>
        </div>
        <div class="col-lg-12">
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex: 2"></div>
                    <div style="flex: 2"><strong>Item</strong></div>
                    <div style="flex: 1"><strong>Price</strong></div>
                    <div style="flex: 1"><strong>Quantity</strong></div>
                    <div style="flex: 1"><strong>Total</strong> </div>
                </div>
                {% for i in items %}
                 <div class="cart-row">
                    <div style="flex: 2"><img class="row-image" src="{{i.product.imgURL}}"></div>
                    <div style="flex: 2">{{i.product.name}}</div>
                    <div style="flex: 1">{{i.product.price|floatformat:2}} DT</div>
                    <div style="flex: 1">
                        <p class="quantity">x{{i.quantity}}</p>
                        <div class="quantity">
                            <img data-product={{i.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static 'images/arrow-up.png' %}">
                            <img data-product={{i.product.id}} data-action="remove" class="chg-quantity update-cart" src="{% static 'images/arrow-down.png' %}">
                        </div>
                    </div>
                    <div style="flex: 1">{{i.get_total}} DT</div>
                </div>
                {% endfor %}
            </div>
            <br>
        </div>
    </div>
{% endblock content %}

store/templates/store/checkout.html
{% extends 'store/index.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="form">
                <div id="user-info">
                    <div class="form-field">
                        <input class="form-control" name="name" placeholder="Name.." required type="text">
                    </div>
                    <div class="form-field">
                        <input class="form-control" name="email" placeholder="Email.." required type="email">
                    </div>
                </div>

                <div id="shipping-info">
                    <hr>
                    <p>Shipping Information:</p>
                    <hr>
                    <div class="form-field">
                        <input class="form-control" name="address" placeholder="Address.." type="text">
                    </div>
                    <div class="form-field">
                        <input class="form-control" name="city" placeholder="City.." type="text">
                    </div>
                    <div class="form-field">
                        <input class="form-control" name="state" placeholder="State.." type="text">
                    </div>
                    <div class="form-field">
                        <input class="form-control" name="zipcode" placeholder="Zip code.." type="text">
                    </div>
                </div>

                <hr>
                <input class="btn btn-secondary btn-block" id="form-button" type="submit" value="Continue">
            </form>
        </div>

        <br>
        <div class="box-element hidden" id="payment-info">
            <small>Paypal Options: &nbsp</small>
            <button id="make-payment" class="btn btn-outline-dark btn-sm">make-payment</button>
        </div>

    </div>

    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
            <hr>
            <h3>Order Summary</h3>
            <hr>
            {% for i in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{i.product.imgURL}}"></div>
                <div style="flex:2"><p>{{i.product.name}}</p></div>
                <div style="flex:1"><p>{{i.product.price|floatformat:2}} DT</p></div>
                <div style="flex:1"><p>x{{i.quantity}}</p></div>
            </div>
            {% endfor %}
            <h5>Items: {{order.get_cart_items}}</h5>
            <h5>Total: {{order.get_cart_total|floatformat:2}} DT</h5>
        </div>
    </div>
</div>

<script type="text/javascript">
    var shipping = '{{order.shipping}}'
    var total = '{{order.get_cart_total|floatformat:2}}'
    if (shipping == 'False') {
        document.getElementById('shipping-info').innerHTML = ''
    }

    if (user != 'AnonymousUser') {
        document.getElementById('user-info').innerHTML = ''
    }

    if (shipping == 'False' && user != 'AnonymousUser') {
        //Hide entire form if user is logged in and shipping is false
        document.getElementById('form-wrapper').classList.add("hidden");
        //Show payment if logged in user wants to buy an item that does not require shipping
        document.getElementById('payment-info').classList.remove("hidden");
    }

    var form = document.getElementById('form')
    form.addEventListener('submit', function (e) {
        e.preventDefault()
        console.log('Form Submitted...')
        document.getElementById('form-button').classList.add("hidden");
        document.getElementById('payment-info').classList.remove("hidden");
    })


    document.getElementById('make-payment').addEventListener('click', function (e) {
        submitFormData()
    })
    function submitFormData() {
        console.log('Payment button clicked')

        var userFormData = {
            'name': null,
            'email': null,
            'total': total,
        }

        var shippingInfo = {
            'address': null,
            'city': null,
            'state': null,
            'zipcode': null,
        }

        if (shipping != 'False') {
            shippingInfo.address = form.address.value
            shippingInfo.city = form.city.value
            shippingInfo.state = form.state.value
            shippingInfo.zipcode = form.zipcode.value
        }

        if (user == 'AnonymousUser') {
            userFormData.name = form.name.value
            userFormData.email = form.email.value
        }

        console.log('Shipping Info:', shippingInfo)
        console.log('User Info:', userFormData)

        var url = "/process_order/"
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify({'form': userFormData, 'shipping': shippingInfo}),

        })
            .then((response) => response.json())
            .then((data) => {
                console.log('Success:', data);
                alert('Transaction completed');

                cart = {}
                document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"

                window.location.href = "{% url 'store' %}"

            })
    }

</script>
{% endblock content %}

store/templates/store/contact_us.html
{% extends 'store/index.html' %}
{% load static %}

{% block title %}
Contact us
{% endblock title %}

{% block content %}
<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us
        directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5">

            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-secondary btn-block mb-4" type="submit">Send</button>
            </form>
        </div>
        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>Sousse, TN</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>+216 21 345 678</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>contact@shopwave.com</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>
</section>
{% endblock content %}

store/templates/store/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <title> {% block title %} ShopWave {% endblock title %} </title>
    <!-- Favicon -->
    <link href="{% static 'images/logo.png' %}" rel="icon" type="image/x-icon type">
    <style>
        link[rel="icon"] {
            width: 100px;
            height: 100px;
        }
    </style>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
    <meta content="" name="Fedi Letaief"/>
    <meta content="" name="description"/>
    <!-- Bootstrap icons-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
    <!-- imported -->
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" rel="stylesheet">
    <!-- Cookies -->
    <script type="text/javascript">
        var user = '{{request.user}}'
        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        const csrftoken = getToken('csrftoken');

        function getCookie(name) {
            // Split cookie string and get all individual name=value pairs in an array
            var cookieArr = document.cookie.split(";");

            // Loop through the array elements
            for (var i = 0; i < cookieArr.length; i++) {
                var cookiePair = cookieArr[i].split("=");

                /* Removing whitespace at the beginning of the cookie name
                and compare it with the given string */
                if (name == cookiePair[0].trim()) {
                    // Decode the cookie value and return
                    return decodeURIComponent(cookiePair[1]);
                }
            }
            // Return null if not found
            return null;
        }

        var cart = JSON.parse(getCookie('cart'))
        if (cart == undefined) {
            cart = {}
            console.log('Cart Created!', cart)
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }
        console.log('Cart:', cart)
    </script>
    {% block head %}
    {% endblock head %}
</head>
<body>
<!-- Navbar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'store' %}">ShopWave</a>
        <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-bs-target="#navbarSupportedContent" data-bs-toggle="collapse" type="button"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a aria-current="page" class="nav-link active" href="{% url 'store' %}">Home</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'contact-us' %}">Contact</a></li>
                {% if user.is_staff %}
                <li class="nav-item"><a class="nav-link" href="{% url 'add-product' %}">Add Product</a></li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"
                       id="navbarDropdown" role="button">Shop</a>
                    <ul aria-labelledby="navbarDropdown" class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'store' %}">All Products</a></li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>

                        {% for c in categories %}
                        <li>
                            <a class="dropdown-item" href="{% url 'store' %}?category={{c.name}}">{{c.name}}</a>
                        </li>
                        {% endfor %}

                    </ul>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-dark" href="{% url 'cart' %}">
                        <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span class="badge bg-dark text-white ms-1 rounded-pill">{{cartItems}}</span>
                    </a>
                </li>
            </ul>
            <div class="d-flex">

                {% if user.is_authenticated %}
                <a class="btn btn-dark" href="{% url 'members:logout_user' %}">Logout</a>
                {% else %}
                <ul class="nav d-flex align-items-center">
                    <li class="nav-item mx-lg-2">
                        <a class="link-offset-1 text-dark-emphasis"
                           href="{% url 'members:register_user' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-dark" href="{% url 'members:login_user' %}">Login</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</nav>
<!-- Navbar-->


<!--Messages-->
<div class="container">
    {% if messages %}
    {% for m in messages %}
    <br>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ m }}
        <button aria-label="Close" class="btn-close" data-bs-dismiss="alert" type="button"></button>
    </div>
    {% endfor %}
    {% endif %}
</div>
<!--Messages-->

<!--Block Content-->
<div class="container">
    <br>
    {% block content %}


    {% endblock content %}
    <br>
    <br>
    <br>
    <br>
</div>
<!--Block Content-->

<!-- Footer-->
<footer class="py-5" id="sticky-footer" style="--bs-bg-opacity: .8;">
    <div class="container"><p class="m-0 text-center text-secondary">Copyright &copy; ShopWave 2023</p></div>
</footer>
<!-- Footer-->

<!-- Core theme JS-->
<script src="{% static 'js/cart.js' %}" type="text/javascript"></script>
<script crossorigin="anonymous"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>