ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls', namespace='members')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'members'
urlpatterns = [
    path('login_user/', views.login_user, name="login_user"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('register_user/', views.register_user, name="register_user"),
    path('password-reset/', PasswordResetView.as_view(template_name='authentication/password_reset.html'),
         name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'),
         name='password_reset_complete'),
]

store/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', StoreView.as_view(), name="store"),
    path('cart/', CartView.as_view(), name="cart"),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('update_item/', UpdateitemView.as_view(), name="update-item"),
    path('process_order/', views.processOrder, name="process-order"),
    path('search_product/', SearchProductView.as_view(), name="search-product"),
    path('contact_us/', views.contact_us, name="contact-us"),
    path('add_product/', views.AddProductView.as_view(), name="add-product"),
    path('update_product/<product_id>', views.update_product, name="update-product"),
    path('delete_product/<product_id>', views.delete_product, name="delete-product"),

]

members/models.py
from django.db import models

# Create your models here.

members/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __int__(self, *args, **kwargs):
        super(RegisterUserForm, self).__int__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

members/views.py
from django.contrib.auth.views import PasswordResetView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm

from members.forms import RegisterUserForm
from store.models import Customer

def login_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('store')
        else:
            messages.success(request, "Error logging in, Try Again..")
            return redirect(request.get_full_path())
    else:
        return render(request, 'authentication/login.html', {})


def logout_user(request):
    logout(request)
    messages.success(request, "Logged Out..")
    return redirect('store')


def register_user(request):
    form = RegisterUserForm()
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            email = form.cleaned_data['email']
            user = authenticate(request, username=username, password=password)
            customer = Customer.objects.create(user=user, name=username, email=email)
            login(request, user)
            messages.success(request, "Registred..")
            return redirect('store')
    return render(request, 'authentication/register.html', {
        'form': form,
    })

members/templates/authentication/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Login Page{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
        {% block content %}
    <br>
    <br>
    <div class="container">
        {% if messages %}
            {% for m in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ m }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

            {% endfor %}
        {% endif %}
    </div>
    <br>
    <div class="container">
        <h2>Login</h2>
        <form acion="" method="POST">
          <!-- Email input -->
            {% csrf_token %}
          <div class="form-outline mb-4">
            <input type="text" id="form2Example1" class="form-control" name="username" />
            <label class="form-label" for="form2Example1">Username</label>
          </div>

          <!-- Password input -->
          <div class="form-outline mb-4">
            <input type="password" id="form2Example2" class="form-control" name="password" />
            <label class="form-label" for="form2Example2">Password</label>
          </div>

          <!-- 2 column grid layout for inline styling -->
          <div class="row mb-4">
            <div class="col d-flex justify-content-center">
              <!-- Checkbox -->
              <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
                <label class="form-check-label" for="form2Example31"> Remember me </label>
              </div>
            </div>

            <div class="col">
              <!-- Simple link -->
              <a href="{% url 'members:password-reset' %}" class="link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Forgot password?</a>
            </div>
          </div>

          <!-- Submit button -->
          <button type="submit" class="btn btn-secondary btn-block mb-4">Log in</button>

          <!-- Register buttons -->
          <div class="text-center">
            <p>Not a member? <a href="{% url 'members:register_user' %}" class="link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Register</a></p>
<!--            <p>or sign up with:</p>-->
<!--            <button type="button" class="btn btn-link btn-floating mx-1">-->
<!--              <i class="fab fa-facebook-f"></i>-->
<!--            </button>-->

<!--            <button type="button" class="btn btn-link btn-floating mx-1">-->
<!--              <i class="fab fa-google"></i>-->
<!--            </button>-->

<!--            <button type="button" class="btn btn-link btn-floating mx-1">-->
<!--              <i class="fab fa-twitter"></i>-->
<!--            </button>-->

<!--            <button type="button" class="btn btn-link btn-floating mx-1">-->
<!--              <i class="fab fa-github"></i>-->
<!--            </button>-->
          </div>
        </form>
    </div>
        {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

members/templates/authentication/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Reset Password</title>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" rel="stylesheet">
</head>
<body>

<div class="shadow p-4 mb-5 bg-body rounded">
    <h1>Reset password</h1>
    <form class="form-inline" method="post">
        {% csrf_token %}
        {% for field in form %}
        {{ field.label_tag }}
        {{ field }}
        {% if field.errors %}
        <small>{{ field.errors|striptags }}</small>
        {% endif %}
        {% endfor %}
        <!--        <br>-->
        <!--        <div class="d-flex align-items-center">-->
        <!--            <br>-->
        <!--            <input class="btn btn-secondary btn-block mb-4" type="submit" value="Send">-->
        <!--            <a class="link-offset-1 text-dark-emphasis" href="{%url 'login' %}">Cancel</a>-->
        <!--        </div>-->
        <div>
            <br>
            <ul class="nav d-flex align-items-center">
                <li class="nav-item">
                    <input class="btn btn-dark" type="submit" value="Send">
                </li>
                <li class="nav-item mx-lg-2">
                    <a class="link-offset-1 text-dark-emphasis"
                       href="{% url 'members:login_user' %}">Cancel</a>
                </li>
            </ul>
        </div>
    </form>
</div>
<script crossorigin="anonymous"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

members/templates/authentication/password_reset_complete.html
<div class="card center">
	<p>Your password has been changed successfully. Please <a href="{% url 'members:login_user' %}">Login</a></p>
</div>
 	

members/templates/authentication/password_reset_confirm.html
<div class="center">
	<form method="post" class="card">
	  {% csrf_token %}
	  <h2>Password Reset Confirm</h2>
	  
	  {% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
	  
	  <div>
	    <button type="submit" class="btn btn-primary">Reset Password</button>
	  </div>
	</form>
</div>

members/templates/authentication/password_reset_done.html
<div class="center card">
	<h2>Reset Password</h2>
	<p>Please check your inbox and follow the instruction to reset your password.</p>
</div>

members/templates/authentication/password_reset_email.html
<p>Hi</p>

<p>You're receiving this email because you requested a password reset for your user account at {{domain}}/</p>

<p>Please click the following link to reset your password:</p>

{{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}

<p>Thanks</p>
<p>Todo App Team</p>

members/templates/authentication/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Registration Page</title>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" rel="stylesheet">
</head>
<body>
<br>
{% if form.errors %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    Error..
    <button aria-label="Close" class="btn-close" data-bs-dismiss="alert" type="button"></button>
</div>
{% endif %}
<br>
<div class="shadow p-4 mb-5 bg-body rounded">
    <h1>Register</h1>
    <form action="{% url 'members:register_user' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-dark" type="submit">Register</button>
        <a class="link-offset-1 text-dark-emphasis"
           href="{% url 'members:login_user' %}">Cancel</a>
    </form>
</div>
<script crossorigin="anonymous"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>